/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.cathering;

import javax.swing.JOptionPane;

/**
 *
 * @author Cika Andhini
 */
public class DataPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form DataPelanggan
     */
    public DataPelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNAMA = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtALAMAT = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtNOTELP = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        btnPESAN = new javax.swing.JButton();
        btnBATAL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("COCOGOOSE", 0, 12)); // NOI18N
        jLabel2.setText("Nama Pemesan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 100, 120, 18);

        txtNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAMAActionPerformed(evt);
            }
        });
        jPanel1.add(txtNAMA);
        txtNAMA.setBounds(180, 90, 450, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 70, 640, 10);

        jLabel1.setFont(new java.awt.Font("BigNoodleTitling", 0, 36)); // NOI18N
        jLabel1.setText("Silahkan Isi Data Dibawah Ini Untuk Verifikasi");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 10, 530, 60);

        jLabel3.setFont(new java.awt.Font("COCOGOOSE", 0, 12)); // NOI18N
        jLabel3.setText("Tanggal Pemesanan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 150, 150, 18);

        jLabel4.setFont(new java.awt.Font("COCOGOOSE", 0, 12)); // NOI18N
        jLabel4.setText("Alamat Tujuan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 210, 110, 18);

        txtALAMAT.setColumns(20);
        txtALAMAT.setRows(5);
        jScrollPane1.setViewportView(txtALAMAT);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 190, 450, 100);

        jLabel5.setFont(new java.awt.Font("COCOGOOSE", 0, 12)); // NOI18N
        jLabel5.setText("Nomor Telepon");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 330, 120, 20);
        jPanel1.add(txtNOTELP);
        txtNOTELP.setBounds(180, 320, 230, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(180, 140, 37, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari ", "Februari", "Maret", "April ", "Mei ", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(230, 140, 100, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", " " }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(350, 140, 80, 30);

        btnPESAN.setFont(new java.awt.Font("COCOGOOSE", 0, 14)); // NOI18N
        btnPESAN.setText("PESAN");
        btnPESAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPESANActionPerformed(evt);
            }
        });
        jPanel1.add(btnPESAN);
        btnPESAN.setBounds(200, 370, 120, 30);

        btnBATAL.setFont(new java.awt.Font("COCOGOOSE", 0, 14)); // NOI18N
        btnBATAL.setText("BATAL");
        jPanel1.add(btnBATAL);
        btnBATAL.setBounds(390, 370, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 490);

        setBounds(0, 0, 681, 465);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNAMAActionPerformed

    private void btnPESANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPESANActionPerformed
        JOptionPane.showMessageDialog(null, "Terima kasih atas pesanan Anda.");
        JOptionPane.showMessageDialog(null, "Paket makanan Anda akan segera kami antar.");
        System.exit(0);
    }//GEN-LAST:event_btnPESANActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBATAL;
    private javax.swing.JButton btnPESAN;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtALAMAT;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextField txtNOTELP;
    // End of variables declaration//GEN-END:variables
}
