/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.cathering;

import javax.swing.JOptionPane;

/**
 *
 * @author Cika Andhini
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnORDERBR = new javax.swing.JButton();
        btnBATAL = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMENU1 = new javax.swing.JButton();
        btnMENU2 = new javax.swing.JButton();
        btnMENU3 = new javax.swing.JButton();
        btnMENU4 = new javax.swing.JButton();
        btnMENU5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnPROSES = new javax.swing.JButton();
        txtTOTAL = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBAYAR = new javax.swing.JTextField();
        btnHITUNG = new javax.swing.JButton();
        txtKEMBALI = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLANJUT = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtMENU4 = new javax.swing.JTextField();
        txtMENU3 = new javax.swing.JTextField();
        txtMENU2 = new javax.swing.JTextField();
        txtMENU1 = new javax.swing.JTextField();
        txtHARGA4 = new javax.swing.JTextField();
        txtHARGA3 = new javax.swing.JTextField();
        txtHARGA2 = new javax.swing.JTextField();
        txtHARGA1 = new javax.swing.JTextField();
        txtJML4 = new javax.swing.JTextField();
        txtJML3 = new javax.swing.JTextField();
        txtJML2 = new javax.swing.JTextField();
        txtJML1 = new javax.swing.JTextField();
        txtSUB1 = new javax.swing.JTextField();
        txtSUB2 = new javax.swing.JTextField();
        txtSUB3 = new javax.swing.JTextField();
        txtSUB4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnORDERBR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnORDERBR.setText("Order Baru");
        btnORDERBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnORDERBRActionPerformed(evt);
            }
        });
        getContentPane().add(btnORDERBR);
        btnORDERBR.setBounds(10, 11, 100, 30);

        btnBATAL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBATAL.setText("Batal");
        btnBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBATALActionPerformed(evt);
            }
        });
        getContentPane().add(btnBATAL);
        btnBATAL.setBounds(120, 10, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("M:\\DOWNLOAD GAMBAR\\menu 1\\grid - Copy.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 130, 270);

        jLabel3.setIcon(new javax.swing.ImageIcon("M:\\DOWNLOAD GAMBAR\\menu2\\grid - Copy.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 80, 140, 270);

        jLabel4.setIcon(new javax.swing.ImageIcon("M:\\DOWNLOAD GAMBAR\\menu3\\grid - Copy.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 80, 140, 270);

        jLabel5.setIcon(new javax.swing.ImageIcon("M:\\DOWNLOAD GAMBAR\\menu4\\grid - Copy.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 80, 130, 270);

        jLabel6.setIcon(new javax.swing.ImageIcon("M:\\DOWNLOAD GAMBAR\\menu5\\grid - Copy.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(720, 80, 130, 270);

        btnMENU1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMENU1.setText("Menu 1");
        btnMENU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMENU1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMENU1);
        btnMENU1.setBounds(20, 360, 130, 30);

        btnMENU2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMENU2.setText("Menu 2");
        btnMENU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMENU2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMENU2);
        btnMENU2.setBounds(190, 360, 140, 30);

        btnMENU3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMENU3.setText("Menu 3");
        btnMENU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMENU3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMENU3);
        btnMENU3.setBounds(370, 360, 140, 30);

        btnMENU4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMENU4.setText("Menu 4");
        btnMENU4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMENU4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMENU4);
        btnMENU4.setBounds(550, 360, 130, 30);

        btnMENU5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMENU5.setText("Menu 5");
        btnMENU5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMENU5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMENU5);
        btnMENU5.setBounds(720, 360, 130, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 410, 860, 10);

        btnPROSES.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPROSES.setText("Proses Transaksi");
        btnPROSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPROSESActionPerformed(evt);
            }
        });
        getContentPane().add(btnPROSES);
        btnPROSES.setBounds(720, 443, 140, 30);
        getContentPane().add(txtTOTAL);
        txtTOTAL.setBounds(720, 490, 140, 30);

        jLabel12.setFont(new java.awt.Font("BigNoodleTitling", 0, 18)); // NOI18N
        jLabel12.setText("Total");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(670, 500, 40, 21);
        getContentPane().add(txtBAYAR);
        txtBAYAR.setBounds(720, 530, 140, 30);

        btnHITUNG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHITUNG.setText("Hitung");
        btnHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHITUNGActionPerformed(evt);
            }
        });
        getContentPane().add(btnHITUNG);
        btnHITUNG.setBounds(720, 580, 140, 30);
        getContentPane().add(txtKEMBALI);
        txtKEMBALI.setBounds(720, 630, 140, 30);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("COCOGOOSE", 0, 24)); // NOI18N
        jLabel1.setText("Yulia's Cathering");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(640, 10, 250, 40);

        jLabel8.setFont(new java.awt.Font("BigNoodleTitling", 0, 18)); // NOI18N
        jLabel8.setText("Nama");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 480, 50, 30);

        btnLANJUT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLANJUT.setText("Lanjut");
        btnLANJUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLANJUTActionPerformed(evt);
            }
        });
        jPanel1.add(btnLANJUT);
        btnLANJUT.setBounds(720, 690, 140, 30);

        jLabel10.setFont(new java.awt.Font("BigNoodleTitling", 0, 18)); // NOI18N
        jLabel10.setText("Jumlah");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(400, 490, 50, 20);
        jPanel1.add(txtMENU4);
        txtMENU4.setBounds(20, 640, 150, 30);
        jPanel1.add(txtMENU3);
        txtMENU3.setBounds(20, 600, 150, 30);
        jPanel1.add(txtMENU2);
        txtMENU2.setBounds(20, 560, 150, 30);
        jPanel1.add(txtMENU1);
        txtMENU1.setBounds(20, 520, 150, 30);
        jPanel1.add(txtHARGA4);
        txtHARGA4.setBounds(200, 640, 150, 30);
        jPanel1.add(txtHARGA3);
        txtHARGA3.setBounds(200, 600, 150, 30);
        jPanel1.add(txtHARGA2);
        txtHARGA2.setBounds(200, 560, 150, 30);
        jPanel1.add(txtHARGA1);
        txtHARGA1.setBounds(200, 520, 150, 30);
        jPanel1.add(txtJML4);
        txtJML4.setBounds(380, 640, 70, 30);
        jPanel1.add(txtJML3);
        txtJML3.setBounds(380, 600, 70, 30);
        jPanel1.add(txtJML2);
        txtJML2.setBounds(380, 560, 70, 30);
        jPanel1.add(txtJML1);
        txtJML1.setBounds(380, 520, 70, 30);
        jPanel1.add(txtSUB1);
        txtSUB1.setBounds(490, 520, 130, 30);

        txtSUB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSUB2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtSUB2);
        txtSUB2.setBounds(490, 560, 130, 30);
        jPanel1.add(txtSUB3);
        txtSUB3.setBounds(490, 600, 130, 30);
        jPanel1.add(txtSUB4);
        txtSUB4.setBounds(490, 640, 130, 30);

        jLabel9.setFont(new java.awt.Font("BigNoodleTitling", 0, 18)); // NOI18N
        jLabel9.setText("Harga");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 490, 50, 20);

        jLabel11.setFont(new java.awt.Font("BigNoodleTitling", 0, 18)); // NOI18N
        jLabel11.setText("Subtotal");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(530, 490, 50, 21);

        jLabel7.setFont(new java.awt.Font("COCOGOOSE", 0, 24)); // NOI18N
        jLabel7.setText("Daftar Menu Masakan ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 420, 320, 30);

        jLabel13.setFont(new java.awt.Font("BigNoodleTitling", 0, 18)); // NOI18N
        jLabel13.setText("Bayar");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(670, 540, 40, 21);

        jLabel14.setFont(new java.awt.Font("BigNoodleTitling", 0, 18)); // NOI18N
        jLabel14.setText("Kembali");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(660, 630, 60, 21);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 790);

        setBounds(0, 0, 924, 774);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPROSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPROSESActionPerformed
        int harga1 = Integer.parseInt(txtHARGA1.getText());
        int jumlah1 = Integer.parseInt(txtJML1.getText());
        int subtotal1 = harga1*jumlah1;
        txtSUB1.setText(""+subtotal1);
        int harga2 = Integer.parseInt(txtHARGA2.getText());
        int jumlah2 = Integer.parseInt(txtJML2.getText());
        int subtotal2 = harga2*jumlah2;
        txtSUB2.setText(""+subtotal2);
        int harga3 = Integer.parseInt(txtHARGA3.getText());
        int jumlah3 = Integer.parseInt(txtJML3.getText());
        int subtotal3 = harga3*jumlah3;
        txtSUB3.setText(""+subtotal3);
        int harga4 = Integer.parseInt(txtHARGA4.getText());
        int jumlah4 = Integer.parseInt(txtJML4.getText());
        int subtotal4 = harga4*jumlah4;
        txtSUB4.setText(""+subtotal4); 
        int sub1 = Integer.parseInt(txtSUB1.getText());
        int sub2 = Integer.parseInt(txtSUB2.getText());
        int sub3 = Integer.parseInt(txtSUB3.getText());
        int sub4 = Integer.parseInt(txtSUB4.getText());
        int hasil = sub1+sub2+sub3+sub4;
        txtTOTAL.setText(""+hasil);
    }//GEN-LAST:event_btnPROSESActionPerformed

    private void btnORDERBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnORDERBRActionPerformed
        txtMENU1.setText("");
        txtMENU2.setText("");
        txtMENU3.setText("");
        txtMENU4.setText("");
        txtHARGA1.setText("");
        txtHARGA2.setText("");
        txtHARGA3.setText("");
        txtHARGA4.setText("");
        txtJML1.setText("");
        txtJML2.setText("");
        txtJML3.setText("");
        txtJML4.setText("");
        txtSUB1.setText("");
        txtSUB2.setText("");
        txtSUB3.setText("");
        txtSUB4.setText("");
        txtTOTAL.setText("");
        txtBAYAR.setText("");
        txtKEMBALI.setText("");
    }//GEN-LAST:event_btnORDERBRActionPerformed

    private void btnHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHITUNGActionPerformed
       int total = Integer.parseInt(txtTOTAL.getText());
       int bayar = Integer.parseInt(txtBAYAR.getText());
       int hasil = bayar-total;
       txtKEMBALI.setText(""+hasil);
    }//GEN-LAST:event_btnHITUNGActionPerformed

    private void btnMENU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMENU1ActionPerformed
        txtMENU1.setText("Udang Saus Padang");
        txtMENU2.setText("Sayur Bayam");
        txtMENU3.setText("Tempe Goreng Tepung");
        txtMENU4.setText("Semangka Potong");        
        txtHARGA1.setText("8000");
        txtHARGA2.setText("4000");
        txtHARGA3.setText("2000");
        txtHARGA4.setText("1000");
    }//GEN-LAST:event_btnMENU1ActionPerformed

    private void btnMENU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMENU2ActionPerformed
        txtMENU1.setText("Ayam Bumbu Rujak");
        txtMENU2.setText("Sayur Asem");
        txtMENU3.setText("Tahu Goreng");
        txtMENU4.setText("Melon Potong");        
        txtHARGA1.setText("9000");
        txtHARGA2.setText("3000");
        txtHARGA3.setText("2000");
        txtHARGA4.setText("1000");
    }//GEN-LAST:event_btnMENU2ActionPerformed

    private void btnMENU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMENU3ActionPerformed
        txtMENU1.setText("Telur Ayam Rebus");
        txtMENU2.setText("Soto AYam Lamongan");
        txtMENU3.setText("Tempe Mendoan");
        txtMENU4.setText("Semangka Potong");        
        txtHARGA1.setText("4000");
        txtHARGA2.setText("9000");
        txtHARGA3.setText("2000");
        txtHARGA4.setText("1000");
    }//GEN-LAST:event_btnMENU3ActionPerformed

    private void btnMENU4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMENU4ActionPerformed
        txtMENU1.setText("Ayam Bakar Madu");
        txtMENU2.setText("Cah Kangkung");
        txtMENU3.setText("Bakwan Jagung");
        txtMENU4.setText("Melon Potong");        
        txtHARGA1.setText("9000");
        txtHARGA2.setText("4000");
        txtHARGA3.setText("2000");
        txtHARGA4.setText("1000");
    }//GEN-LAST:event_btnMENU4ActionPerformed

    private void btnMENU5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMENU5ActionPerformed
        txtMENU1.setText("Rolade Asam Manis");
        txtMENU2.setText("Sop Ayam");
        txtMENU3.setText("Tahu Goreng Tepung");
        txtMENU4.setText("Jeruk");        
        txtHARGA1.setText("9000");
        txtHARGA2.setText("4000");
        txtHARGA3.setText("2000");
        txtHARGA4.setText("1000");
    }//GEN-LAST:event_btnMENU5ActionPerformed

    private void btnBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBATALActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Yakin nggak mau pesan makanannya?", "Pintu Keluar", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_btnBATALActionPerformed

    private void txtSUB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSUB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSUB2ActionPerformed

    private void btnLANJUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLANJUTActionPerformed
        new DataPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLANJUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBATAL;
    private javax.swing.JButton btnHITUNG;
    private javax.swing.JButton btnLANJUT;
    private javax.swing.JButton btnMENU1;
    private javax.swing.JButton btnMENU2;
    private javax.swing.JButton btnMENU3;
    private javax.swing.JButton btnMENU4;
    private javax.swing.JButton btnMENU5;
    private javax.swing.JButton btnORDERBR;
    private javax.swing.JButton btnPROSES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtBAYAR;
    private javax.swing.JTextField txtHARGA1;
    private javax.swing.JTextField txtHARGA2;
    private javax.swing.JTextField txtHARGA3;
    private javax.swing.JTextField txtHARGA4;
    private javax.swing.JTextField txtJML1;
    private javax.swing.JTextField txtJML2;
    private javax.swing.JTextField txtJML3;
    private javax.swing.JTextField txtJML4;
    private javax.swing.JTextField txtKEMBALI;
    private javax.swing.JTextField txtMENU1;
    private javax.swing.JTextField txtMENU2;
    private javax.swing.JTextField txtMENU3;
    private javax.swing.JTextField txtMENU4;
    private javax.swing.JTextField txtSUB1;
    private javax.swing.JTextField txtSUB2;
    private javax.swing.JTextField txtSUB3;
    private javax.swing.JTextField txtSUB4;
    private javax.swing.JTextField txtTOTAL;
    // End of variables declaration//GEN-END:variables
}
